### ISSUE TITLE
Current Temperature error

### ISSUE THREAD

**Issue by Visi84** [normen/homebridge-platform-maxcube#43]
Good morning,
for some time I get the following error in the homebridge log.

_[09/01/2022, 12:09:22] [homebridge-platform-maxcube] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info._

The temperature on the Home app is always the same and does not measure the room temperature correctly.

**System Information**
Sistema operativo	Raspbian GNU/Linux Buster (10)
Versione Node.js	v14.16.0
Versione npm	v6.14.11

**Comment by normen** [comment]
Seems like your cube doesn't send infos anymore. Can you control the thermostats using the MAX! app? Very common for t he cube to stop working after a while, especially when in Manual mode. No way to debug with so few info.

**Comment by Visi84** [comment]
I can control it correctly with the Max app, both from mobile and from computer.
I restarted the cube and the raspberry to make sure it wasn't my problem before posting.
I also installed the latest versions of node and npm to rule out version errors.

I attach the logs by activating the homebridge debug mode.

[09/01/2022, 16:00:03] [homebridge-platform-maxcube] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[09/01/2022, 16:00:03] [homebridge-platform-maxcube] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1569:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at Thermostat.getCurrentTemperature (/usr/local/lib/node_modules/homebridge-platform-maxcube/thermostat.js:216:5)
    at Characteristic.emit (node:events:390:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1542:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)

**Comment by normen** [comment]
So you have the phone app active? Then you can't use this plugin. Check the README.
